# Generated by Django 5.2.1 on 2025-05-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_location_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_pinned',
            field=models.BooleanField(default=True),
        ),
    ]
