# Generated by Django 5.2.1 on 2025-05-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_category_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='place',
            name='is_pinned',
            field=models.BooleanField(default=True),
        ),
    ]
