# Generated by Django 5.2.1 on 2025-05-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_category_is_pinned_place_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
