# Generated by Django 5.2.1 on 2025-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='popullar',
            field=models.BooleanField(default=False),
        ),
    ]
