# Generated by Django 5.2.1 on 2025-05-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_popullar'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='beautifull',
            field=models.BooleanField(default=False),
        ),
    ]
